import { and, asc, eq, isNull, or } from "drizzle-orm";
import { db } from "@/db";
import { agentActions, conversations, messages } from "@/db/schema/agent";
import { auditEvents } from "@/db/schema/audit";
import type { JsonObject } from "@/db/schema/types";
import type { CheckoutReadiness } from "@/modules/cart/checkout-readiness";
import type { CheckoutPreparation } from "@/modules/checkout/checkout-proposal";
import { isAgentOutcome, type AgentOutcome } from "./agent-outcome";
import { openCurrentConversation } from "./conversation-repository";
import {
  CHECKOUT_ACTION_MESSAGE,
  CHECKOUT_READINESS_ACTION_MESSAGE,
  checkoutActionEntry,
  checkoutReadinessActionEntry,
  parseCustomerActionEntry,
  type CheckoutActionEntry,
  type CheckoutReadinessActionEntry,
  type CustomerActionEntry,
} from "./customer-action-entry";
import {
  createEmptyConversationContext,
  parseConversationContext,
  type ShoppingIntent,
} from "./intent";

/**
 * The message role that carries the Customer's side of the Transcript.
 *
 * The recorder and the loader share it, so an entry can never be written under
 * a role the Transcript does not read back.
 */
const TRANSCRIPT_MESSAGE_ROLE = "CUSTOMER" as const;

export type ConversationTranscriptTurn = {
  id: string;
  customerMessage: string;
  result: AgentOutcome | null;
  error: string | null;
};

/**
 * One Customer-visible record in the Transcript: a Conversation Turn the
 * Customer typed, or an entry generated by an explicit Customer UI action.
 */
export type ConversationTranscriptEntry =
  | ConversationTranscriptTurn
  | CustomerActionEntry;

export type CurrentConversation = {
  conversationId: string;
  transcript: ConversationTranscriptEntry[];
  contextSummary: ShoppingIntent;
  revision: number;
};

export interface ConversationState {
  loadCurrent(): Promise<CurrentConversation | null>;
  resetCurrent(): Promise<void>;
  /**
   * Records one Review for checkout as a durable Customer Action Entry.
   *
   * The entry carries generated provenance and the deterministic readiness
   * card. Conversation Context is left untouched, so the Commerce Agent never
   * receives the entry as Customer-authored text.
   */
  recordCheckoutReadiness(
    readiness: CheckoutReadiness,
  ): Promise<CheckoutReadinessActionEntry>;
  /**
   * Records one Check out command as a durable Customer Action Entry.
   *
   * The entry keeps whichever answer the checkout authority gave — a prepared
   * proposal, a blocking readiness result, or an explanation — so a reload
   * shows what the Customer was actually asked to approve rather than a fresh
   * preparation of a since-changed Cart. Conversation Context is untouched, so
   * the Commerce Agent never receives it as Customer-authored text.
   */
  recordCheckout(
    preparation: CheckoutPreparation,
  ): Promise<CheckoutActionEntry>;
}

/**
 * Reads one persisted Customer-side message back as a Transcript entry.
 *
 * An entry generated by a Customer UI action reloads with its provenance and
 * the deterministic result it recorded. A typed Conversation Turn reloads with
 * its Agent outcome, or — when the Agent was unavailable — as the retryable
 * failure the Customer saw rather than a result.
 *
 * @param message - Persisted Customer-side message row.
 * @returns The Transcript entry to render.
 */
export function transcriptEntryFromMessage(message: {
  id: string;
  content: string;
  metadata: JsonObject;
}): ConversationTranscriptEntry {
  const customerAction = parseCustomerActionEntry(message);
  if (customerAction) return customerAction;

  const outcome = message.metadata.agentOutcome;
  const persistedOutcome = isAgentOutcome(outcome) ? outcome : null;
  const error =
    persistedOutcome?.status === "TEMPORARILY_UNAVAILABLE"
      ? persistedOutcome.message
      : null;
  return {
    id: message.id,
    customerMessage: message.content,
    result: error ? null : persistedOutcome,
    error,
  };
}

export function createConversationState(
  guestSessionId: string,
): ConversationState {
  /**
   * Appends one generated Customer-side entry to the current Conversation.
   *
   * Both Customer UI actions record the same way — open the Conversation,
   * append the entry, touch the Conversation — so neither can drift into
   * writing a Transcript row the loader would not read back.
   */
  async function recordCustomerAction(
    content: string,
    metadata: JsonObject,
  ): Promise<string> {
    return db.transaction(async (transaction) => {
      const conversation = await openCurrentConversation(
        transaction,
        guestSessionId,
      );
      const [entry] = await transaction
        .insert(messages)
        .values({
          conversationId: conversation.id,
          role: TRANSCRIPT_MESSAGE_ROLE,
          content,
          metadata,
        })
        .returning({ id: messages.id });
      await transaction
        .update(conversations)
        .set({ updatedAt: new Date() })
        .where(eq(conversations.id, conversation.id));
      return entry.id;
    });
  }

  return {
    async loadCurrent() {
      const [current] = await db
        .select({ id: conversations.id, context: conversations.context })
        .from(conversations)
        .where(
          and(
            eq(conversations.guestSessionId, guestSessionId),
            isNull(conversations.closedAt),
          ),
        )
        .limit(1);
      if (!current) return null;

      const transcriptRows = await db
        .select({
          id: messages.id,
          content: messages.content,
          metadata: messages.metadata,
        })
        .from(messages)
        .where(
          and(
            eq(messages.conversationId, current.id),
            eq(messages.role, TRANSCRIPT_MESSAGE_ROLE),
          ),
        )
        .orderBy(asc(messages.createdAt), asc(messages.id));
      const context = parseConversationContext(current.context);
      return {
        conversationId: current.id,
        transcript: transcriptRows.map(transcriptEntryFromMessage),
        contextSummary: context.productConstraints,
        revision: context.revision,
      };
    },

    async recordCheckoutReadiness(readiness) {
      const { content, metadata } = checkoutReadinessActionEntry(readiness);
      const id = await recordCustomerAction(content, metadata);

      return {
        id,
        action: "CHECKOUT_READINESS",
        message: CHECKOUT_READINESS_ACTION_MESSAGE,
        provenance: "GENERATED",
        readiness,
      };
    },

    async recordCheckout(preparation) {
      const { content, metadata } = checkoutActionEntry(preparation);
      const id = await recordCustomerAction(content, metadata);
      return {
        id,
        action: "CHECKOUT",
        message: CHECKOUT_ACTION_MESSAGE,
        provenance: "GENERATED",
        preparation,
      };
    },

    async resetCurrent() {
      await db.transaction(async (transaction) => {
        const [current] = await transaction
          .select({ id: conversations.id })
          .from(conversations)
          .where(
            and(
              eq(conversations.guestSessionId, guestSessionId),
              isNull(conversations.closedAt),
            ),
          )
          .limit(1);
        if (!current) return;

        const [[action], [audit]] = await Promise.all([
          transaction
            .select({ id: agentActions.id })
            .from(agentActions)
            .where(eq(agentActions.conversationId, current.id))
            .limit(1),
          transaction
            .select({ id: auditEvents.id })
            .from(auditEvents)
            .where(
              and(
                eq(auditEvents.entityId, current.id),
                or(
                  eq(auditEvents.entityType, "Conversation"),
                  eq(auditEvents.entityType, "CONVERSATION"),
                ),
              ),
            )
            .limit(1),
        ]);
        if (!action && !audit) {
          await transaction
            .delete(conversations)
            .where(eq(conversations.id, current.id));
          return;
        }

        await transaction
          .delete(messages)
          .where(eq(messages.conversationId, current.id));
        await transaction
          .update(conversations)
          .set({
            closedAt: new Date(),
            context: createEmptyConversationContext(),
            updatedAt: new Date(),
          })
          .where(eq(conversations.id, current.id));
      });
    },
  };
}
