import type { JsonObject } from "@/db/schema/types";
import {
  isCheckoutReadiness,
  type CheckoutReadiness,
} from "@/modules/cart/checkout-readiness";

/**
 * The fixed text of the Review for checkout entry.
 *
 * The Customer never types it, so it stays constant for every readiness result
 * and can never be mistaken for Customer-authored text.
 */
export const CHECKOUT_READINESS_ACTION_MESSAGE = "Review my Cart for checkout";

/**
 * A Conversation entry produced by an explicit Customer UI action.
 *
 * It sits on the Customer's side of the Transcript because the Customer
 * initiated it, and it always carries its generated provenance and the
 * deterministic result the Storefront produced.
 */
export type CustomerActionEntry = {
  id: string;
  action: "CHECKOUT_READINESS";
  message: string;
  provenance: "GENERATED";
  readiness: CheckoutReadiness;
};

type PersistedMessage = {
  id: string;
  content: string;
  metadata: JsonObject;
};

/**
 * Builds the durable Transcript record for one Review for checkout action.
 *
 * The readiness card is stored beside the fixed text, so a later reload shows
 * the exact Cart version, Items, Cart Prices, and Cart Subtotal that were
 * evaluated rather than a re-evaluation of a since-changed Cart.
 *
 * @param readiness - Deterministic readiness result to retain.
 * @returns The message content and metadata to persist.
 */
export function checkoutReadinessActionEntry(readiness: CheckoutReadiness): {
  content: string;
  metadata: JsonObject;
} {
  return {
    content: CHECKOUT_READINESS_ACTION_MESSAGE,
    metadata: {
      customerAction: {
        type: "CHECKOUT_READINESS",
        provenance: "GENERATED",
        readiness,
      },
    },
  };
}

/**
 * Reads a persisted message back as a Customer Action Entry.
 *
 * An ordinary Customer message, and an action whose readiness card is missing
 * or unrecognized, return `null` so the Transcript never presents typed text as
 * generated or an entry without the result it recorded.
 *
 * @param message - Persisted Customer-side message row.
 * @returns The reloaded entry, or `null` when the row is not one.
 */
export function parseCustomerActionEntry(
  message: PersistedMessage,
): CustomerActionEntry | null {
  const action = message.metadata.customerAction;
  if (typeof action !== "object" || action === null) return null;
  const { type, readiness } = action as {
    type?: unknown;
    readiness?: unknown;
  };
  if (type !== "CHECKOUT_READINESS" || !isCheckoutReadiness(readiness)) {
    return null;
  }

  return {
    id: message.id,
    action: "CHECKOUT_READINESS",
    message: CHECKOUT_READINESS_ACTION_MESSAGE,
    provenance: "GENERATED",
    readiness,
  };
}

/**
 * Whether a Transcript entry was generated by a Customer UI action rather than
 * produced by a Conversation Turn.
 */
export function isCustomerActionEntry(
  entry: unknown,
): entry is CustomerActionEntry {
  if (typeof entry !== "object" || entry === null) return false;
  const { provenance, action } = entry as {
    provenance?: unknown;
    action?: unknown;
  };
  return provenance === "GENERATED" && action === "CHECKOUT_READINESS";
}
