import type {
  AgentOutcome,
  AgentResponse,
} from "@/modules/agent/agent-outcome";
import type { CustomerActionEntry } from "@/modules/agent/customer-action-entry";

export type { CurrentConversation } from "@/modules/agent/conversation-state";
export type { CustomerActionEntry } from "@/modules/agent/customer-action-entry";
export type { ShoppingIntent } from "@/modules/agent/intent";

export type AgentResult = AgentOutcome | AgentResponse;

export type ConversationTurn = {
  id: number | string;
  customerMessage: string;
  result: AgentResult | null;
  error: string | null;
};

/**
 * One record in the Customer-visible Transcript: a Conversation Turn the
 * Customer typed, or an entry generated by an explicit Customer UI action.
 */
export type TranscriptEntry = ConversationTurn | CustomerActionEntry;

export type CartFeedback = {
  kind: "success" | "error";
  message: string;
};
